"""add menu and diets

Revision ID: 060ee334d9af
Revises: 
Create Date: 2026-02-03 15:58:43.776940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '060ee334d9af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diets',
    sa.Column('problematic_component', sa.String(length=100), nullable=False),
    sa.Column('diet', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('problematic_component', 'diet')
    )
    op.create_table('menu_plan',
    sa.Column('date', sa.String(length=50), nullable=False),
    sa.Column('meal', sa.String(length=200), nullable=False),
    sa.Column('portions', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['meal'], ['recipes.name'], ),
    sa.PrimaryKeyConstraint('date', 'meal')
    )
    op.create_table('preferences',
    sa.Column('ingredient_group', sa.String(length=100), nullable=False),
    sa.Column('problematic_component', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_group'], ['nutrients.ingredient_group'], ),
    sa.PrimaryKeyConstraint('ingredient_group', 'problematic_component')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('preferences')
    op.drop_table('menu_plan')
    op.drop_table('diets')
    # ### end Alembic commands ###
